/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    teams: Team;
    players: Player;
    matches: Match;
    stadiums: Stadium;
    media: Media;
    photos: Photo;
    videos: Video;
    staff: Staff;
    'newsletter-subscriptions': NewsletterSubscription;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    stadiums: StadiumsSelect<false> | StadiumsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Rôle de l'utilisateur dans le système
   */
  role: 'admin' | 'director' | 'secretary' | 'treasurer' | 'coach' | 'parent' | 'photographer';
  /**
   * Prénom
   */
  firstName: string;
  /**
   * Nom de famille
   */
  lastName: string;
  /**
   * Numéro de téléphone (pour SMS et WhatsApp)
   */
  phone?: string | null;
  /**
   * Équipe gérée par cet entraîneur
   */
  team?: (number | null) | Team;
  /**
   * Préférences de notification
   */
  notificationPreferences?: {
    sms?: boolean | null;
    push?: boolean | null;
    email?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * Nom de l'équipe (ex: U15, N1, etc.)
   */
  name: string;
  /**
   * Catégorie de l'équipe
   */
  category: 'U7' | 'U9' | 'U11' | 'U13' | 'U15' | 'U17' | 'N1' | 'N4';
  ageGroup?: ('youth' | 'senior') | null;
  /**
   * Description de l'équipe
   */
  description?: string | null;
  /**
   * Entraîneur(s) de l'équipe
   */
  coach?: (number | User)[] | null;
  /**
   * Horaires d'entraînement
   */
  trainingSchedule?: {
    day1?: string | null;
    day2?: string | null;
  };
  /**
   * Lieu d'entraînement
   */
  venue?: string | null;
  /**
   * Couleur de l'équipe (hex code)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * Prénom
   */
  firstName: string;
  /**
   * Nom de famille
   */
  lastName: string;
  fullName?: string | null;
  /**
   * Photo du joueur
   */
  photo?: (number | null) | Media;
  /**
   * Date de naissance
   */
  birthDate: string;
  /**
   * Équipe
   */
  team: number | Team;
  /**
   * Numéro de maillot
   */
  jerseyNumber?: number | null;
  /**
   * Poste
   */
  position?: ('forward' | 'defense' | 'goalie') | null;
  /**
   * Parents/Tuteurs
   */
  parents: {
    /**
     * Compte parent
     */
    parent: number | User;
    /**
     * Lien de parenté
     */
    relationship?: ('father' | 'mother' | 'guardian') | null;
    id?: string | null;
  }[];
  /**
   * Notes médicales (visible uniquement par les admins)
   */
  medicalNotes?: string | null;
  /**
   * Contact d'urgence
   */
  emergencyContact?: {
    name?: string | null;
    phone?: string | null;
    relationship?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texte alternatif pour l'accessibilité
   */
  alt: string;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * Date et heure du match
   */
  date: string;
  /**
   * Équipe adversaire
   */
  opponent: string;
  /**
   * Catégorie/Équipe qui joue
   */
  category: number | Team;
  location: 'home' | 'away';
  /**
   * Nom de la salle
   */
  venue?: string | null;
  /**
   * Stade externe (avec itinéraire)
   */
  stadium?: (number | null) | Stadium;
  status: 'upcoming' | 'live' | 'completed' | 'cancelled';
  /**
   * Score des Jokers
   */
  scoreJokers?: number | null;
  /**
   * Score de l'adversaire
   */
  scoreOpponent?: number | null;
  /**
   * Match actuellement en direct
   */
  isLive?: boolean | null;
  /**
   * Résumé du match
   */
  summary?: string | null;
  /**
   * Disponibilité des joueurs pour ce match
   */
  playerAvailability?:
    | {
        /**
         * Joueur
         */
        player: number | Player;
        /**
         * Statut de disponibilité
         */
        status: 'available' | 'unavailable' | 'maybe';
        /**
         * Déclaré par (parent/coach)
         */
        declaredBy: number | User;
        /**
         * Date de déclaration
         */
        declaredAt?: string | null;
        /**
         * Notes (ex: blessure, retard prévu)
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stadiums".
 */
export interface Stadium {
  id: number;
  /**
   * Nom du stade/gymnase
   */
  name: string;
  /**
   * Adresse complète
   */
  address: string;
  /**
   * Ville
   */
  city: string;
  /**
   * Code postal
   */
  postalCode?: string | null;
  /**
   * Lien Google Maps pour l'itinéraire
   */
  googleMapsUrl?: string | null;
  /**
   * Informations sur le parking, accès PMR, etc.
   */
  parkingInfo?: string | null;
  /**
   * Photo du stade
   */
  photo?: (number | null) | Media;
  /**
   * Notes supplémentaires (vestiaires, buvette, etc.)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * Titre de la photo
   */
  title: string;
  /**
   * Description de la photo
   */
  description?: string | null;
  /**
   * Image
   */
  imageUrl: number | Media;
  /**
   * Catégorie de la photo
   */
  category?: ('match' | 'training' | 'event' | 'team') | null;
  /**
   * Match associé
   */
  match?: (number | null) | Match;
  /**
   * Ajouté par
   */
  uploadedBy: number | User;
  /**
   * Statut d'approbation (seuls les admins/directeurs peuvent modifier)
   */
  approvalStatus: 'pending' | 'approved' | 'rejected';
  /**
   * Raison du rejet
   */
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Titre de la vidéo
   */
  title: string;
  /**
   * Description de la vidéo
   */
  description?: string | null;
  /**
   * ID YouTube (ex: dQw4w9WgXcQ)
   */
  youtubeId: string;
  /**
   * Catégorie de la vidéo
   */
  category?: ('highlights' | 'interviews' | 'training' | 'event') | null;
  /**
   * Match associé
   */
  match?: (number | null) | Match;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  /**
   * Nom complet
   */
  name: string;
  /**
   * Fonction au sein du club
   */
  role: 'coach' | 'assistant_coach' | 'president' | 'secretary' | 'treasurer' | 'equipment_manager' | 'volunteer';
  /**
   * Équipe gérée (si applicable)
   */
  team?: (number | null) | Team;
  /**
   * Photo de profil
   */
  photo?: (number | null) | Media;
  /**
   * Biographie
   */
  bio?: string | null;
  /**
   * Email de contact
   */
  email?: string | null;
  /**
   * Téléphone
   */
  phone?: string | null;
  /**
   * Ordre d'affichage
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: number;
  /**
   * Adresse email
   */
  email: string;
  /**
   * Abonné
   */
  subscribed?: boolean | null;
  /**
   * Date de désabonnement
   */
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'stadiums';
        value: number | Stadium;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: number | NewsletterSubscription;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  team?: T;
  notificationPreferences?:
    | T
    | {
        sms?: T;
        push?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  ageGroup?: T;
  description?: T;
  coach?: T;
  trainingSchedule?:
    | T
    | {
        day1?: T;
        day2?: T;
      };
  venue?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  photo?: T;
  birthDate?: T;
  team?: T;
  jerseyNumber?: T;
  position?: T;
  parents?:
    | T
    | {
        parent?: T;
        relationship?: T;
        id?: T;
      };
  medicalNotes?: T;
  emergencyContact?:
    | T
    | {
        name?: T;
        phone?: T;
        relationship?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  date?: T;
  opponent?: T;
  category?: T;
  location?: T;
  venue?: T;
  stadium?: T;
  status?: T;
  scoreJokers?: T;
  scoreOpponent?: T;
  isLive?: T;
  summary?: T;
  playerAvailability?:
    | T
    | {
        player?: T;
        status?: T;
        declaredBy?: T;
        declaredAt?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stadiums_select".
 */
export interface StadiumsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  postalCode?: T;
  googleMapsUrl?: T;
  parkingInfo?: T;
  photo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  imageUrl?: T;
  category?: T;
  match?: T;
  uploadedBy?: T;
  approvalStatus?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeId?: T;
  category?: T;
  match?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  team?: T;
  photo?: T;
  bio?: T;
  email?: T;
  phone?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  email?: T;
  subscribed?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}